### PR TITLE
fix: outline icons not visible without explicit color prop

### PR DESCRIPTION
**Pull request by mrotaru**
# Description

In storybook, icons are passed to the link-list component as a React component with an explicitly set colour; however when rendered from Contentful, the icon comes through as a string prop, in which case the colour passed to the icon component is an empty string. The outline icons do have a default colour, however the empty string prop means it does not apply and the svg is generated with `color` and `fill` attributes without a value, making the outline white and therefore invisible on white backgrounds:

Screenshot from 2021-12-15 15-08-58

This PR "hardcodes" the outline colour:

Screenshot from 2021-12-15 15-13-03

# Checklist

Pull request contains:

- [ ] A new component
- [x] Component maintenance: improvement / bug fix / etc
- [ ] Component library change: storybook / webpack / etc

Definition of done:

- [x] Includes theme changes for both Uswitch and money
- [x] Work has been tested in multiple browsers
- [x] PR description includes description of change
- [x] PR description includes screenshot of change
- [ ] If new component, designer has approved screenshot
- [ ] If the change will affect other teams, that team knows about this change
- [ ] If introducing a new component behaviour, added a story to cover that case.

### CODE REVIEW

**Review by samhstn — COMMENTED** [review]
Can we not default an empty string that comes from contentful to `'#141414'` and make the colour still configurable?

**Review by samhstn — COMMENTED** [review]
Do you want to make this change in fs-core here: https://github.com/uswitch/fs-core/tree/master/src/components/legacy/icon

**Comment by mrotaru** [comment]
> Can we not default an empty string that comes from contentful to `'#141414'` and make the colour still configurable?

The empty string doesn't come from contentful though - it's from the LinkList component. The more elegant solution was to modify the Icon component and make the color an optional prop - in that case everything would work as expected for these icons but could potentially cause issues for other icons which, given that it's currently a mandatory prop, would assume it's always set. I checked some of them and should be fine but not all so hardcoding the color seemed like the least intrusive solution, given that we already have icons that have hardcoded colors and we don't even need configurable colors for these icons at the moment.

**Comment by mrotaru** [comment]
> Does it make sense to make this change in fs-core here: https://github.com/uswitch/fs-core/tree/master/src/components/legacy/icon

One less repository to change, that would be good. Although that would leave trustyle slightly broken, wouldn't it ? It's quite unlikely to occur in practice, but still possible. I'd say let's fix it in trustyle, and then migrate changes to fs-core ?

**Review by samhstn — APPROVED** [review]

**Review by samhstn — APPROVED** [review]

**Pull request merged**
