### PR TITLE
fix: change width in logo collection for money theme

### PR DESCRIPTION
**Pull request by meghaniankov**
# Description

Changed logo collection width in Money theme. Fixes bug that was causing smaller images to not render.

# Checklist

Pull request contains:

- [ ] A new component
- [x] Component maintenance: improvement / bug fix / etc
- [ ] Component library change: storybook / webpack / etc

Definition of done:

- [ ] Includes theme changes for both Uswitch and money
- [x] Work has been tested in multiple browsers
- [x] PR description includes description of change
- [ ] PR description includes screenshot of change
- [ ] If new component, designer has approved screenshot
- [ ] If the change will affect other teams, that team knows about this change
- [ ] If introducing a new component behaviour, added a story to cover that case.
- [ ] If component change, version updated

### CODE REVIEW

**Comment by domtronn** [comment]
@meghaniankov, have you tried this on taller logos like EE?
It can be tricky to get the aspect ratio right for all logos

**Comment by domtronn** [comment]
We have a providers API with all logos in, maybe it's worth using this in a trustyle story so we can test what these changes do to all logos?

https://providers-api-production.internal.usw.co/api/providers

**Comment by jonathan-fielding** [comment]
> https://providers-api-production.internal.usw.co/api/providers

The api is internal and trustyle is open source so we can't use that within storybook, making sure we use some good examples tho is good idea tho

**Comment by domtronn** [comment]
> > https://providers-api-production.internal.usw.co/api/providers
> 
> The api is internal and trustyle is open source so we can't use that within storybook, making sure we use some good examples tho is good idea tho, Percy should be able to show whether this change has had negative impact

It's not internal https://www.uswitch.com/api/providers

**Comment by jonathan-fielding** [comment]
Ok we can factor that into further improvements

**Pull request merged**
